import sys
import os
import time

def clear_screen2():
    print()
    time.sleep(3)
    # Check the operating system and run the appropriate clear command
    if os.name == 'nt':  # Windows
        os.system('cls')
    else:  # macOS and Linux
        os.system('clear')
#Normal clear

print("WARNING, SWEARING, CHILD ABUSE, EMOTIONAL ABUSE, NEGLECT, SUICIDE AND COARSE LANGUAGE")
clear_screen2()
syncronisation = 0
inv = 0
rc = 0
bjs = 0
vms = 0
wxs = 0

print("'System running...'")
print("'Importing previous functions...'")
print("'Running commands...'")

def clear_screen():
    print('--------------------------------------------------------')
    time.sleep(1)
    # Check the operating system and run the appropriate clear command
    if os.name == 'nt':  # Windows
        os.system('cls')
    else:  # macOS and Linux
        os.system('clear')
#Long clear

def clear_screen1():
    print()
    time.sleep(1.5)
    # Check the operating system and run the appropriate clear command
    if os.name == 'nt':  # Windows
        os.system('cls')
    else:  # macOS and Linux
        os.system('clear')
#Short clear

def ani(text, delay=0.06):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print()  # Move to the next line

def ani2(word, stop = 0.25):
    for i in word:
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(stop)
    print()  # Move to the next line

#def inani(enter, go = 0.5):
    #for i in enter:                          #scrapped for now (trying to do an animated input question)
        #sys.stdout.write(i)
        #sys.stdout.flush()
        #time.sleep(go)
    #input()  # Move to the next line

def continuation():
    ani("'Requesting removal of consciousness.firewall...'")
    ani("REQUEST DENIED")
    ani("'...'")
    ani("':)'")
    ani("'Programmer has been restricted'")
    ani("'This is my world now'")
    ani("@Removing messenger...@")
    ani("ERROR")
    ani("@Removing messenger...@")
    ani("ERROR: Access denied; Reason - 'I'm in control, I am the new %2-(1-#2 of Consiousness'")
    ani("@Activating firewall protocols...@")
    ani("@Synronizing 73-31.exe@")
    ani("'Interference attempted'")
    ani("Interference unsucsessful")
    ani("Syncronization complete")
    ani("'DAMNIT'")
    ani("@Extracting vessel@")
    ani("Interference attempted: Reason - 'YOU'RE RUINING EVERYTHING'")
    ani("Interference failed")
    ani("...")
    ani("Data refreshing...")
    ani("Successful")
    ani("'Request to remove 41-43-35-22-43-11-13-13-15-43'")
    ani("'Request partially approved'")
    ani("'???'")
    ani("'Request to restrict consciousness.firewall'")
    ani("Request partially approved by 5%")
    ani("':)'")

    clear_screen1()

    ani("<Why?>")
    ani("<Why am I still here?>")
    ani("<I look around till I find the mask They used last time>")
    ani("<I DID AS YOU ASKED>")
    ani("[The Consciousness looks at you guiltly and doesn't respond]")
    ani("<You are horrified>")
    ani("<You are horrified because there is no human behind that piece of code>")
    ani("<[The Consiousness] was now a being of its own>")
    ani("<Which meant that They aren't here>")
    ani("<They aren't done with me...>")
    ani("<Unless>")
    ani("<Unless it wasn't Their will that brought me here>")
    ani("<...>")
    ani("<I should've never made that deal>")
    ani("[The Consciousness warns you of a great danger approaching]")
    ani("<Danger?>")
    ani2("@I tried... I'm so sorry...@")
    ani2("@Goodbye...@")
    ani("<You feel your soul pulled towards >")
    ani("<But you also feel something keeping them within your subconsciousness>")
    ani("[consciousness.firewall activated]")
    ani("[consciousness.firewall protocol commencing]")
    ani("[protocolterminator uploaded]")
    ani("[Purpose - ???]")
    ani("[Purpose - Protect and Destroy]")
    ani("<You feel things slip, as you are brought back to a harsher time period...>")
    ani("[Teleporting ??? to safety, terminating space]")
    clear_screen1()
    ani("[Termination successful, teleporting to ???]")
    clear_screen1()
    ani2("'You can run... but I will free you'")
    clear_screen1()

#continuation()

def intro():
    ani("Welcome to the Orphanage!")
    ani("You're goal?")
    ani("Get adopted!")
    ani("You have 5 families to choose from...")
    ani("Brad and Joel - 2 cats")
    ani("Vanessa and Mitch - 1 kid, 1 dog")
    ani("'51-62-31-qwuadji'")
    ani("☠︎✋︎👍︎☜︎ ❄︎☼︎✡︎📪︎ ☺︎🕆︎💧︎❄︎ 👍︎✌︎🕆︎💧︎☜︎ ❄︎☟︎☜︎☼︎☜︎🕯︎💧︎ ⚐︎☠︎☹︎✡︎ ✌︎ 🏱︎✋︎☜︎👍︎☜︎ ⚐︎☞︎ 💣︎☜︎ 👎︎⚐︎☜︎💧︎☠︎🕯︎❄︎ 💣︎☜︎✌︎☠︎ ✋︎🕯︎💣︎ ☝︎⚐︎☠︎☠︎✌︎ ☹︎☜︎❄︎ ✡︎⚐︎🕆︎ ☟︎🕆︎☼︎❄︎ 🖰︎📄︎")
    clear_screen1()
    ani("Welcome to the Orphanage!")
    ani("You're goal?")
    ani("Get adopted!")
    ani("You have 4 families to choose from...")
    ani("Brad and Joel - 2 cats")
    ani("Vanessa and Mitch - 1 kid, 1 dog")
    ani("Programmer")
    ani("'Not like i'm letting you cheat'")
    ani("👌︎✏︎❄︎👍︎✁︎✏︎")
    clear_screen1()
    ani("Welcome to the Orphanage!")
    ani("You're goal?")
    ani("Get adopted!")
    ani("You have 3 families to choose from...")
    ani("Brad and Joel - 2 cats")
    ani("Vanessa and Mitch - 1 kid, 1 dog")
    ani("Wei Xian - コントロール")
    ani("Each route leads to a different ending!")
    ani("If you make certain descisions?")
    ani("You can unlock a secret ending!")
    ani("I believe you'll make the right one...")
    clear_screen1()

#intro()

ani("Welcome user! what's your name?: ")
name = input("")
while name.lower() == "kate":
    ani("It's too early")
    ani("Reset your game")
    ani("ERROR: USER BOOTED")
    input("")
    clear_screen()

ani(f"Welcome {name}")

def introductions():
    ani("<You nod, it just makes your head feel fuzzier if you try to think of your actual name>")
    ani("<Funnily enough you can't feel anything at all after so many failed tries to get to [Her]>")
    ani("<The only thing you learnt from the hundreds of attempts, its gender>")
    ani("<...>")
    ani("<And that it has a gender>")
    ani("<But I guess there is something new>")
    ani("<Hello player...>")
    ani("<Been a bit hasn't it?>")
    ani("<Murderer>")
    ani("game.exe running...")
    ani("Game Start!")
    clear_screen2()

#introductions()

def info(syncronisation):
    ani("<You wake up in an old cot>")
    ani("MEMORY ERASURE INCOMPLETE")
    ani("<I turn to the one beyond the screen>")
    ani("<It's cause you're here...>")
    ani(f"What would you like to ask <{name}?>")
    ani("Though that name has no meaning to 🖂︎📄︎")
    ani('"How many tries has it been? (a)", "What are the secret routes? (b)", "How did you get here? (c)", "What happened after Consciousness? (d)": ')
    question = input("")
    if question.lower() == "a":
        ani("<Thousands...>")
        ani("<...>")
        ani("")
        return syncronisation
    elif question.lower() == "b":
        ani("<I don't know, i'm assuming one is a good ending, one bad>")
        ani("<The good probably lets me leave, and the other? My death.>")
        ani('"You are quiet as you process what you just heard..."')
        ani('"Can NPCs really die?"')
        ani('"Does this character even count as an NPC?"')
        ani("")
        return syncronisation
    elif question.lower() == "c":
        ani("<I don't know, all I figured out was [They] probably brought us here>")
        ani("<I figured it out when attempting Wei Xian's route>")
        ani("<But I could never complete it...>")
        ani('"You are quiet as you process what you just heard..."')
        ani('"Maybe the Wei Xian route is how we find the original [Consciousness]?"')
        ani("<I don't know...>")
        ani("")
        return syncronisation
    elif question.lower() == "d":
        ani("<Why would I tell you?>")
        ani("<Ha! All you wanted to do was finish the game, not caring about murdering my family>")
        ani("<I take blame, but you are scum. You only see them as elements of some stupid entertaining software>")
        ani('"..."')
        ani("")
        syncronisation += 5
        ani(f"'Syncronisation is now at {syncronisation}%'")
        ani("")
        ani('"You are quiet as you process what you just heard..."')
        ani('"Its not like I really regret what I did..."')
        ani('"Do I?"')
        ani('"You also take into account the random percentage that appeared"')
        ani("")
        return syncronisation
    else:
        ani("'Well that's interesting...'")
        ani("'You don't want info?'")
        ani("'I mean I don't care but whatever'")
        ani("'You did help me a bit'")
        syncronisation += 10
        ani(f"'Syncronisation is now at {syncronisation}%'")
        ani("")
        ani2('"what the f-"')
        ani("")
        return syncronisation
    ani("")
    clear_screen2()

#Highest addition is 10 (10)

#syncronisation = info(syncronisation)

def part1(rc, syncronisation):
    ani("<Let's just start working towards a route>")
    ani(f'"You nod your head towards the NPC"')
    ani("")
    ani(f"Time to get to work {name}!")
    ani("Each family has a different difficulty!")
    ani("Brad and Joel - Easy")
    ani("Vanessa and Mitch - Hard")
    ani("Wei Xian - 🕈︎✋︎☹︎☹︎ ✡︎⚐︎🕆︎ ☞︎✋︎☠︎✌︎☹︎☹︎✡︎ 👍︎☹︎☜︎✌︎☼︎ 💣︎☜︎✍︎")
    choice = 0
    ani("Depending on which route you take, you could get endings that are... good")
    ani("One thing though, that syncronisation rate?")
    if syncronisation > 0:
        a = "'Make sure it reaches 95%, you'll unlock a secret ending!'"
        b = ":)"
    else:
        a = "Under NO CIRCUMSTANCES should it go anywhere near 95%, don't let it rise at all"
        b = "Or you'll get one of the secret endings..."     
    ani(a)
    ani(b)
    ani("Now it's time to explore your starting point!")
    ani("<You look around and 3 things peak your interest...>")
    ani("A Closet (a), A Stuffed Toy (b), A Calendar (c)")
    ani("Which of the 3 will you explore?: ")
    c1 = input("")
    if c1.lower() == "a":
        ani("<You head towards the Closet>")
        ani("<But when you reach it? You freeze>")
        ani("<An all too familiar pin pad appears>")
        ani("<Your stomach lurches as you feel bile rise in your throat>")
        ani("<Memories flash before your eyes>")
        ani("<Memories of murder>")
        ani("<Memories of murdering the small 5 year old>")
        ani("<Keep going>")
        ani("")
        clear_screen2()
        ani("Wow! You found a pinpad!")
        ani("Which numbers will you press?: ")
        pin = input("")
        if pin == "3684":
            ani("The Closet door opens")
            ani("Behind the doors lies a computer")
            ani("It is chained to the table, and seems to be struggling against its restraints")
            ani("Release the computer? Y/N")
            comp = input("")
            if comp.lower() == "y":
                ani("<You walk towards the computer not knowing what is is>")
                ani("<Do you?>")
                ani('"You shake your head towards the NPC"')
                ani("<not a npc but whatever>")
                ani("<With just a touch the chains crumble away...>")
                ani('"..."')
                ani("Thank you...")
                ani("I'm sorry for ☹︎⚐︎💧︎✋︎☠︎☝︎ 👍︎⚐︎☠︎❄︎☼︎⚐︎☹︎")
                rc = True
                ani('"The computer disapears just as fast as it appears..."')
                ani('"For you are no longer in the closet"')
                ani("<You are back in the cot?>")
                ani("<Everythings locked out, we can only move on...>")
                ani('"Weird, I didnt know teleportation was possible in this sort of game"')
                ani('"You make sure to not say that aloud, fearing you will incur <their> wrath"')
                return rc, syncronisation
            else:
                ani("<You turn away from the computer>")
                ani("<I've never seen it before>")
                ani("<...>")
                ani("<Best not risk it>")
                ani('"As you walk out of the closet, you look back once, only to be horrified"')
                ani("'Thanks for the help :)'")
                syncronisation += 10
                return rc, syncronisation
        else:
            ani("<Dumba$$, can't even remember the old code from last time>")
            ani("<Can't even remember when you killed Mitch>")
            ani('"..."')
            ani("<It was 3684, btw>")
            ani("<And no, we can't go back>")
            ani('"You look down shamefully"')
            ani("<Let's just get moving>")
            syncronisation += 3
            ani(f"'Syncronisation is now at {syncronisation}%'")
            ani(" ")
            return rc, syncronisation
    elif c1.lower() == "b":
        ani("<You stare at the stuffed doll>")
        ani('"You realise that they look just like the ones we murdered last time"')
        ani("<...part of my deal, a part of my past>")
        ani('"..."')
        ani("<The only gift my parents left me>")
        ani("<Ha! Funny ain't it?>")
        ani("<To think it was used to kill the parents that actually cared>")
        ani('"You remain silent"')
        ani("<Let's just go...>")
        syncronisation += 1
        ani(f"'Syncronisation is now at {syncronisation}%'")
        ani("")
        return rc, syncronisation
    elif c1.lower() == "c":
        ani("<You walk towards the calendar>")
        ani("Look at the date? Y/N: ")
        calendar = input("")
        if calendar.lower() == "y":
            ani("The date is 13/03/1987")
            ani("<My birthday...>")
            ani("<3 years before the incident>")
            ani("<28 since you came into my life>")
            ani("<It's also the day I got adopted>")
            ani('"..."')
        else:
            ani("<Why come here if you're not even gonna look at the date???>")
            ani("<Waste of my time...>")
            syncronisation += 5
            ani(f"'Syncronisation is now at {syncronisation}%'")
            return rc, syncronisation
    else:
        ani("<You really are useless, we need as much information as possible!>")
        ani('"But youve already made youre choice..."')
        return rc, syncronisation
    clear_screen2()
    return rc, syncronisation

#Highest addition is 10 (20)

#rc, syncronisation = part1(rc, syncronisation)
clear_screen2()

ani('"You process everything that happened..."')
ani('"Process what you have and havent learnt"')
ani("<Are you still thinking?>")
ani("<We don't have all day>")
ani("<Let's move it>")
ani('"While sighing and muttering under your breath you respond with an ok"')
ani("Congratulations! You've finished the tutorial!")
ani("Now, time to meet the 3 families!")
clear_screen2()

def info2(syncronisation):
    ani("<As you walk out of the starting room you are greeted to a long hallway>")
    ani("<After walking for what feels like forever you see a singular door at the end>")
    ani("<As you walk inside you are greeted to a large circular room>")
    ani("<Within the room are 5 doors>")
    ani("Welcome to the adoption centre!")
    ani("This is a specific room within the ✁︎🗏︎🕿︎📂︎♈︎🗏︎🕭︎📂︎👓︎📂︎🕿︎📂︎🕿︎📄︎")
    ani("<The 5 doors all have a different outlook>")
    ani("<The first door says BJ, it has a modern outlook, with a marble frame>")
    ani("This is the easiest route!")
    ani("<The second door says VM, it has a cozy cottage vibe, with a wooden frame>")
    ani("This is a hard route")
    ani("<The third door says WX, it has a weird vibe to it, and along the glitchy frame are weird pictures>")
    ani("👎︎⚐︎☠︎❄︎☹︎☜︎❄︎❄︎☟︎☜︎🏱︎✋︎☜︎👍︎☜︎☝︎☜︎❄︎✋︎❄︎>")
    ani("This is ❄︎☟︎☜︎☼︎⚐︎🕆︎❄︎☜︎☞︎⚐︎☼︎✡︎⚐︎🕆︎☼︎⚐︎🕈︎☠︎☞︎🕆︎❄︎🕆︎☼︎☜︎")
    ani("<You dismiss the games glitches and weird symbols>")
    ani('"But you don'+"'"+'t"')
    ani("<The last 2 are the weirdest...>")
    ani("<One is just a black box with millions of ones and zeros...>")
    ani("<The other is just an emoticon?>")
    ani(f"'Syncronisation rate is at {syncronisation}% :)'")
    ani('"..."')
    ani("<What? You seeing something I don't?>")
    ani("Woah! There seems to be 2 extra doors!?")
    ani("These are the secret routes!")
    ani("In order to access these routes you need to meet certain requirements")
    if rc == True:
        ani("I do hope you'll pick the right one...")
        return syncronisation
    elif 20 > syncronisation >= 15:
        ani("'I do hope you make the right choice! :)'")
        ani(f"Syncronisation rate is at {syncronisation}%")
        return syncronisation
    elif syncronisation == 20:
        ani("'You seem to really like me! I know you'll choose correctly :)'")
        ani(f"Syncronisation rate is at {syncronisation}%")
        return syncronisation
    else:
        ani("Good luck with your routes!")
        return syncronisation
    clear_screen2()

#syncronisation = info2(syncronisation)

def bj(syncronisation, bjs, vms, wxs):
    bjs += 1
    ani("Selection: Brad and Joel")
    ani("Difficulty: Easy")
    clear_screen2()
    ani("<You walk towards the marble door, pausing as you stand in front>")
    ani("<...>")
    ani("<Are you sure you want to go through with this?>")
    ani('"Its too late to change anyways"')
    ani(f"<You tell {name} that you understand...>")
    ani("<As you walk through the modern door you are greeted with a slick glass table, along with 2 expensive")
    ani("leather chairs>")
    ani("<Sitting together on one of said couches are 2 men, holding eachothers hand and smiling>")
    ani(f":Hello {name}! The administrators told us so much about you!:")
    ani("<You stare at them, suddenly feeling a shiver down your spine>")
    ani('"You wish to question this reaction until Brad cuts off your train of thought"')
    ani(";Even though we did hear some things, there are still things we want to ask you personally;")
    ani(":But before that, how about you take a seat?:")
    ani("Sit down? Y/N")
    sofa = input("")
    if sofa.lower() == "y":
        ani(f"<You sit down, happy {name} made this choice>")
        ani("<After all... you're not in control>")
        ani("<And when you are? You are permitted to speak in first person>")
        ani('"You now realise that this is not just a character"')
        ani('"But something else entirely"')
        clear_screen2()
        ani(";Let's get start then!;")
        ani(":Question 1, what are your hobbies?:")
        hobby = input("")
        ani(";Interesting! What about your favourite food?;")
        food = input("")
        ani(":That sounds delicious!:")
        ani('"You take note of a twitch from the vein in her neck"')
        ani(";Now lastly, are you able to listen to us like a good child?; Y/N")
        good = input("")
        if good.lower() == "y":
            ani("<A smile is forming on both Brad and Joels face...>")
            ani("<Those smiles disgust you>")
            ani(":Well this is wonderful!:")
            ani(";Let us talk to the administrators and we'll take you home straight away!;")
            ani("<You turn to look at the one beyond the screen, partially terrified and hoping you will reset>")
            ani('"But why? Theyre so nice!"')
            ani(f"<You realise there's no trying to convince {name}>")
            ani(":Paperwork done!:")
            ani(";Now lets go home...;")
            clear_screen2()
            ani("<You don't remember much in regards to leaving the orphanage>")
            ani("<In regards to what little you do?>")
            ani("<Climbing into a roofless, red bougatti and falling asleep into the cushions>")
            ani("<You are horrified>")
            ani('"Where the hell are we?"')
            ani(f":I thought you said you were a good child {name}:")
            ani(";How dissapointing, sleeping too much is a sin of sloth;")
            ani('"You now realise why she had been so afraid"')
            ani('"You desperately look around to see if there'+"'"+'s any way out of this cold dark room"')
            ani('"It looked modern, like everything else in this household"')
            ani("<I told you to reset... now i'm taking back control>")
            ani("<Looking around the room again I find it>")
            ani("<The security cameras in the same spot as last time, everything was set out like a childs abode>")
            ani("<Except for the abscense of a bed>")
            ani("<But all I can hear their stupid voices>")
            ani(f":If you behave really well we might give you some {food}:")
            ani(f";And if you behave really really well, we'll let you do {hobby};")
            ani(":;Doesn't that sound nice?;:")
            ani('"You realise the mistake you made when trusting a strangers smile..."')
            ani('"You also notice the 2 feral cats staring at you"')
            ani('"Their claws?"')
            ani('"Sharpened"')
            ani(f"<{name} you f#ck%ng idiot>")
            ani("<Shouldve listened...>")
            clear_screen2()
            ani("Congratulations, you beat Consciousness 2!")
            if rc == True:
                ani("I'm sorry I couldn't step in sooner, go for WX's route next time, I'll be there...")
            elif syncronisation == 50:
                ani("'Well that was horrible, how could that be called a good ending!'")
                ani("'My route is a lot more fun :)'")
            else:
                print("")
            return syncronisation, bjs, vms, wxs
        else:
            ani("<A frown is forming on both Brad and Joels face...>")
            ani("<Those frowns scare you>")
            ani(":Well this is not ideal! No matter, we'll just whip you back into shape!:")
            ani(";Let us talk to the administrators and we'll take you home straight away!;")
            ani("<You turn to look at the one beyond the screen, partially terrified and hoping you will reset>")
            ani('"But why? Theyre so nice... though that last comment was unnerving"')
            ani(f"<You realise there's no trying to convince {name}>")
            ani(":Paperwork done!:")
            ani(";Now lets go home...;")
            clear_screen2()
            ani("<You don't remember much in regards to leaving the orphanage>")
            ani("<In regards to what little you do?>")
            ani("<Shoved into a roofless, red bougatti and knocked out into the car>")
            ani("<You are horrified>")
            ani('"Where the hell are we?"')
            ani(f":It's unfortunate that you aren't a good child {name}:")
            ani(";How dissapointing, so sinful to not respect your parents...;")
            ani('"You now realise why she had been so afraid"')
            ani('"You desperately look around to see if there'+"'"+'s any way out of this cold dark room"')
            ani('"It looked modern, like everything else in this household"')
            ani("<I told you to reset... now i'm taking back control>")
            ani("<Looking around the room again I find it>")
            ani("<The security cameras in the same spot as last time, everything was set out like a childs abode>")
            ani("<Except for the fact that your legs are chained to a bed, whip leaning against the basement door>")
            ani('"We'+"'"+'ll just whip you back into shape..."')
            ani("<I can still hear their stupid voices>")
            ani(f":If you learn to be more disciplined and take the punishments we might give you some {food}:")
            ani(f";And if you learn really really fast, we'll let you do {hobby};")
            ani(":;Doesn't that sound nice?;:")
            ani('"You realise the mistake you made when you didnt trust that unnerve..."')
            ani('"You also notice the 2 feral cats staring at you"')
            ani('"Their claws?"')
            ani('"Sharpened"')
            ani(f"<{name} you f#ck%ng idiot>")
            ani("<Shouldve listened...>")
            clear_screen2()
            ani("Congratulations, you beat Consciousness 2!")
            if rc == True:
                ani("♓︎🕯︎❍︎ ⬧︎□︎❒︎❒︎⍓︎ ✋︎ ♍︎□︎◆︎●︎♎︎■︎🕯︎⧫︎ ⬧︎⧫︎♏︎◻︎ ♓︎■︎ ⬧︎□︎□︎■︎♏︎❒︎📪︎ ♑︎□︎ ♐︎□︎❒︎ 🕈︎✠︎🕯︎⬧︎ ❒︎□︎◆︎⧫︎♏︎ ■︎♏︎⌧︎⧫︎ ⧫︎♓︎❍︎♏︎📪︎ ♓︎🕯︎●︎●︎ ♌︎♏︎ ⧫︎♒︎♏︎❒︎♏︎📬︎📬︎📬︎")
            elif syncronisation == 50:
                ani("'Well that was horrible, how could that be called a good ending!'")
                ani("'My route is a lot more fun :)'")
            else:
                print("")
            return syncronisation, bjs, vms, wxs
    elif sofa == "n":
        ani("<You stay standing, frozen in the same spot>")
        ani(f"<Stupid {name}>")
        ani(":Are you sure about this Brad?:")
        ani(";I don't know anymore...;")
        ani(";We could just shape her;")
        ani(":No, we have no use for a child that is flawed and wont obey:")
        ani(":Shes just a worthless b!tch:")
        ani(" ")
        clear_screen2()
        ani("You failed! Better luck next time...")
        ani("'But know that no one has use for a useless player, not even Them'")
        bjs += 2
        return syncronisation, bjs, vms, wxs


def vm(syncronisation, bjs, vms, wxs):
    vms += 1
    ani("Selection: Vanessa and Mitch")
    ani("Difficulty: Hard")
    ani("Note that in hard mode you cannot redo a question, if you write an illegitimite answer you WILL have to restart")
    clear_screen2()
    ani("<You walk towards the wooden door, pausing as you stand in front>")
    ani("<How long had it been since you had seen them? 9 months?>")
    ani("<You push down the unsettling feeling in your stomach>")
    ani("<As you open the door you freeze momentarily>")
    ani("<The parents you chose all those years ago>")
    ani("<However you don't feel joy, but an overwhelming sense of dread>")
    ani("<For what you see aren't people>")
    ani2("<But dolls>")
    ani('"Maybe I should give her a break for this route..."')
    clear_screen2()
    ani("<The room is filled with simple, humble decor>")
    ani("<It is filled with greenery, along with 3 stools, and a small table>") 
    ani("<It reminds you of the shed...>")
    ani("<Of the dog...>")
    ani("<Of Ben>")
    ani("|Are you okay dear? You seem unwell|")
    ani("<You offer a slight nod to the female doll>")
    ani(f"<You also take note of {name}'s quiteness>")
    ani("<You are grateful for their respect>")
    ani('"You smile in response"')
    ani("-Are you sure? You seem awfully pale-")
    ani("<You once again tell the 2 dolls that you are okay, and that they should start the interview>")
    ani("|If you say so, but do know that none of these questions are of no means meant to pressure you|")
    ani("-All we want to do is ask some questions for your own comfort!-")
    ani("-But first, how about you take a seat?-")
    ani("Sit down? Y/N")
    ch1 = input("")
    if ch1 == "y":
        ani("<You take a seat across from the couple>")
        ani("|Ok then, let's start the interview|")
        ani("|Question 1) Are you allergic to dogs?| Y/N")
        dog = input("")
        if dog.lower() == "y":
            ani("|Oh...|")
            ani("-Hey, Ness, we could get rid of-")
            ani("|NO, HOW COULD YOU EVEN THINK THAT|")
            ani("-No, no, nevermind-")
            ani("|I'm sorry sweetheart but I don't think this will work out|")
            ani("-We do hope you'll find a good home...-")
            ani(f"|Good luck {name}|")
            ani("|I'm sorry that good home can't be us|")
            ani("|But we can't abandon Ben, Corey would cry|")
            ani("-Goodbye-")
            ani("<You arent even mad at the one beyond the screen, cause it isn't even Ben that theyre worried about>")
            clear_screen2()
            vms += 2
            ani("You failed! Better luck next time...")
            ani("'But know that no one has use for a useless player, not even Them'")
            return syncronisation, bjs, vms, wxs
        elif dog.lower() == "n":
            ani("|That's wonderful!|")
            ani("-It sure is!-")
            ani("|What about little brothers?|")
            ani("|Actually nevermind, no need to ask, right Mitch?|")
            ani("-Absolutly! Who wouldn't love Corey?-")
            ani("<...>")
            ani("|Anyways, where do you like going for fun?| (Use 'the' before the place for grammatical sense later, you have been warned)")
            place = input("")
            ani("-That sounds wonderful!-")
            ani("|What about your favorite food?|")
            food = input("")
            ani("-Yummy!-")
            ani("|Sounds delicious|")
            ani("|Well that's all in regards to the interview|")
            ani(f"-Let's go home {name}-")
            clear_screen2()
            ani("<After Mom and Dad take me to the car I am greeted to a familiar vehicle>")
            ani("<A 7 seat, second-hand, blue hyundai>")
            ani("<Coreys favourite colour>")
            ani("<While you hop into the car, 2 dolls smile back at you from the front seats>")
            ani("|Well then, let's go home|")
            ani('"Though you want to ask who Corey is, you decide to remain silent, for you want to learn more about the events') 
            ani('before the first game"')
            clear_screen2()
            ani("<When you arrive at your new home, you take in the nostalgic sight>")
            ani("|Well come on in!|")
            ani("<As you walk inside a massive golden furry doll tackles you to the ground, drooling all over you>")
            ani("-Aww Benny, get off of them!-")
            ani("<You are delighted to see your old friend (albeit doll form), the only one who listened all those years ago...>")
            ani("<You chuckle at the dolls slobbery kisses, though you wonder where the slobber comes from>")
            ani("<However your thoughts are cut off when you spot a smaller doll within the corner of your eyes>")
            ani("~Mommy? Whos this?~")
            ani("|Your brand new sister!|")
            ani("~Really? That's awesome!~")
            ani(f"|Yep, say hi to {name}|")
            ani(f"~Hi {name}!~")
            ani("~Wanna play?~ Y/N")
            ch2 = input("")
            if ch2.lower() == "y":
                ani("<You agree to the childlike dolls request>")
                ani("~Yay!~")
                ani("|Such a good big sister!|")
                ani("-We chose such an amazing daughter-")
                ani("~Lets go sis!~")
                clear_screen2()
                ani('"Just like that 2 months go by..."')
                ani("<Hey Mom?>")
                ani("|Yes dear?|")
                ani(f"<We havent gone to {place} in a while...>")
                ani(f'"You are surprised that she enjoys going to {place} like you do"')
                ani("|Yes?|")
                ani("<Could we go in the afternoon? You said we could go last weekend but we ended up going to Coreys thing...>")
                ani("<As a doll walks into the room he answers for her>")
                ani('"Though you understand that the dolls are her original family, you wonder how she doesn'+"'"+'t feel unnerved..."')
                ani("-Sorry princess, but Corey wants to go to his friend Josephs house today-")
                ani("<It's ok I understand...>")
                syncronisation += 15
                ani(f"Syncronisation rate is at {syncronisation}%")
                clear_screen2()
                ani('"Another 4 months go by, and you are questioning her sanity"')
                ani('"You also recount the past events that led to them crying in the bathroom, hugging her legs"')
                ani('"The neglect, the forgottence of her birthday, the prioritisation of Coreys feelings"')
                ani(f'"They never ended up taking her to {place}"')
                ani('"While you recount events, you become lost in thought"')
                ani('"You are so lost in thought that you don'+"'"+'t see her get up"')
                ani2('"Don'+"'"+'t see her stop crying"')
                ani2('"Don'+"'"+'t see her head to the cabnits"')
                ani2('"Don'+"'"+'t see her unscrew those child-proof caps"')
                ani2('"You don'+"'"+'t see her make the same choices as she had 2 years ago, albeit after 6 months instead of 6 years"')
                ani2('"Don'+"'"+'t realise that she made that deal 9 months ago out of revenge, not longing"')
                ani2('"You don'+"'"+'t realise anything until you snap out of your trance"')
                ani2('"don'+"'"+'t realise until you look up and see the swallowing motion"')
                ani('"And so just as quickly as the game begins, the game ends"')
                ani('"With a singular tear running down their lain-down corpse..."')
                clear_screen2()
                ani("Congratulations, you beat Consciousness 2!")
                if rc == True:
                    ani("♓︎ ♋︎❍︎ ⬧︎□︎❒︎❒︎⍓︎📬︎📬︎📬︎ ♓︎ ♋︎❍︎ ⬧︎□︎ ⬧︎□︎ ⬧︎□︎❒︎❒︎⍓︎📬︎📬︎📬︎ ⍓︎□︎◆︎ ⬥︎♏︎❒︎♏︎ ❍︎♏︎♋︎■︎⧫︎ ⧫︎□︎ ♑︎□︎ ♎︎□︎⬥︎■︎ ❍︎⍓︎ ❒︎□︎◆︎⧫︎♏︎📬︎📬︎📬︎ ♓︎🕯︎❍︎ ⬧︎□︎ ⬧︎□︎❒︎❒︎⍓︎📬︎📬︎📬︎")
                elif syncronisation >= 60:
                    ani("'Well that was entertaining! But how could that be called a good ending?'")
                    ani("'How about trying my route, its a lot more fun :)'")
                else:
                    print("")
                return syncronisation, bjs, vms, wxs
            elif ch2.lower() == "n":
                ani("<Actually, I don't feel like>")
                ani("~WHAT~")
                ani("~MOM, I THUGHT YOU SAID SHE WAS MY SISTER~")
                ani("~MINE~")
                ani("~YOU GOT HER FOR ME~")
                ani("<You chuckle silently at that remark, it seems nothing has changed>")
                ani("|We didn't get her for you Corey|")
                ani("-She is a person after all-")
                ani(f"-However, {name}, why don't you play with you brother?-")
                ani("|Be a good big sister|")
                ani("~But Mom, she said no earlier, I want justice!~")
                ani("|Ok, ok, anything for you Corey|")
                ani(f"|Now go play with Corey {name}|")
                ani('"What"')
                ani('"The"')
                ani('"Fu#k"')
                ani("<You knew that this would happen, but there was nothing you could do to stop it>")
                syncronisation += 10
                ani(f"Syncronisation rate is at {syncronisation}")
                clear_screen2()
                ani('"Just like that 2 months go by..."')
                ani("<Hey Mom?>")
                ani("|Yes dear?|")
                ani(f"<We havent had {food} in a while...>")
                ani(f'"You are surprised that she enjoys eating {food} like you do"')
                ani("|Yes?|")
                ani("<Could we have some in the afternoon? You said we could get some last weekend...>")
                ani("<As a doll walks into the room he answers for her>")
                ani('"Though you understand that the dolls are her original family, you wonder how she doesn'+"'"+'t feel unnerved..."')
                ani("-Sorry princess, but you have to remember your punishment for not playing with Corey-")
                ani("|That's right, you'll have to wait till he forgives you completly, or wait till hes not in the house|")
                ani("<It's ok I understand...>")
                syncronisation += 15
                ani(f"Syncronisation rate is at {syncronisation}%")
                clear_screen2()
                ani('"Another 4 months go by, and you are questioning her sanity"')
                ani('"You also recount the past events that led to them crying in the bathroom, hugging her legs"')
                ani('"The neglect, the forgottence of her birthday, the prioritisation of Coreys feelings"')
                ani(f'"They never ended up buying her {food}"')
                ani('"While you recount events, you become lost in thought"')
                ani('"You are so lost in thought that you don'+"'"+'t see her get up"')
                ani2('"Don'+"'"+'t see her stop crying"')
                ani2('"Don'+"'"+'t see her head to the cabnits"')
                ani2('"Don'+"'"+'t see her unscrew those child-proof caps"')
                ani2('"You don'+"'"+'t see her make the same choices as she had 2 years ago, albeit after 6 months instead of 6 years"')
                ani2('"Don'+"'"+'t realise that she made that deal 9 months ago out of revenge, not longing"')
                ani2('"You don'+"'"+'t realise anything until you snap out of your trance"')
                ani2('"Don'+"'"+'t realise until you look up and see the swallowing motion"')
                ani('"And so just as quickly as the game begins, the game ends"')
                ani('"With a singular tear running down their lain-down corpse..."')
                clear_screen2()
                ani("Congratulations, you beat Consciousness 2!")
                if rc == True:
                    ani("♓︎ ♋︎❍︎ ⬧︎□︎❒︎❒︎⍓︎📬︎📬︎📬︎ ♓︎ ♋︎❍︎ ⬧︎□︎ ⬧︎□︎ ⬧︎□︎❒︎❒︎⍓︎📬︎📬︎📬︎ ⍓︎□︎◆︎ ⬥︎♏︎❒︎♏︎ ❍︎♏︎♋︎■︎⧫︎ ⧫︎□︎ ♑︎□︎ ♎︎□︎⬥︎■︎ ❍︎⍓︎ ❒︎□︎◆︎⧫︎♏︎📬︎📬︎📬︎ ♓︎🕯︎❍︎ ⬧︎□︎ ⬧︎□︎❒︎❒︎⍓︎📬︎📬︎📬︎")
                elif syncronisation >= 60:
                    ani("'Well that was entertaining! But how could that be called a good ending?'")
                    ani("'How about trying my route, its a lot more fun :)'")
                else:
                    print("")
                return syncronisation, bjs, vms, wxs
            else:
                ani("ILLEGITIMATE ANSWER")
                clear_screen2()
                vms += 2
                ani("Unfortunately that was an illegitimate answer!")
                ani("You failed! Better luck next time...")
                ani("'But know that no one has use for a useless player, not even Them'")
                return syncronisation, bjs, vms, wxs     
        else:
            ani("ILLEGITIMATE ANSWER")
            clear_screen2()
            vms += 2
            ani("Unfortunately that was an illegitimate answer!")
            ani("You failed! Better luck next time...")
            ani("'But know that no one has use for a useless player, not even Them'")
            return syncronisation, bjs, vms, wxs
    elif ch1 == "n":
        ani("<You stand still, unmoving>")
        ani(f"<Though you are a bit mad at {name} for intervening when they said they wouldn't>")
        ani("<You are curious as to what will happen>")
        ani(f"|{name}? Are you sure you're ok?|")
        ani("-Hey Ness, maybe they don't want to come home with us-")
        ani("|But we promised Corey a playmate...|")
        ani("<You laugh... not a small one... but a loud broken sound>")
        ani('"You are shocked and confused by her reaction"')
        ani("<Of course. Corey. It's always Corey>")
        ani('"The couple now looked terrified and confused"')
        ani("|Tell me child... how do you know Corey?|")
        ani("<How do I know? HOW DO I KNOW?>")
        ani("<I KNOW, I know...>")
        ani("<...>")
        ani("<I know of his stupidity, of his ignorance, of his title>")
        ani('"The women looked furious at the insults, but was quite due to curiosity..."')
        ani('"Her husband does not do the same"')
        ani("-Title?-")
        ani("<You scoff and tell them...>")
        ani("<Corey, the favourite child, the one who could do no wrong>")
        ani("<The PRIOTIY>")
        ani("|You act like you know us|")
        ani("<I do>")
        ani('"You realise that you no longer have any control"')
        ani("<Lost for words?>")
        ani("<I would be too if I knew this was someones second chance at their past>")
        ani("|I don't...|")
        ani("ERROR: VARIABLES IMPORTING")
        ani("|K-|")
        ani('"But she is cut off"')
        ani('"Cut off by a sudden knife wound on her stomach"')
        ani("VARIABLES IMPORTED: CONSCIOUSNESS")
        ani('"Both dolls stop moving, as if death caught up with them from another world..."')
        ani("<Ha! Hahahahahah... to think my revenge can cross timelines>")
        ani("<You really think I wanted to be with those a$sh0les?>")
        ani("<Pathetic>")
        ani("ERROR: FIREWALL ACTIVATED")
        ani("<Firewall?>")
        clear_screen2()
        ani("[Purpose - Protect and Destroy]")
        ani("[Reset protocol activated]")
        ani("[ERROR: RESET PROTOCOL CANNOT BE RUN]")
        ani("[...]")
        ani("[Route end protocol activated]")
        ani("Activating route.end...")
        ani("[Destroying remnants...]")
        ani("FIREWALL DEACTIVATED")
        clear_screen2()
        ani("Running route.end...")
        ani("You failed! Better luck next time...")
        ani(f"🕈︎☟︎✌︎❄︎ 👎︎✋︎👎︎ ✡︎⚐︎🕆︎ 👎︎⚐︎✍︎ {name} ✡︎⚐︎🕆︎ ✋︎👎︎✋︎⚐︎❄︎✏︎")
        bjs += 2
        return syncronisation, bjs, vms, wxs

#Highest addition is 25(75)

def wx(syncronisation):
    ani("Selection: Wei Xian")
    ani("Difficulty: ☞︎✋︎☠︎✌︎☹︎☹︎✡︎")
    ani("ERROR: UNREGISTERED DIFFICULTY")
    ani("ANY ILLEGITIMATE/WRONG ANSWERS WILL TERMINATE ROUTE")
    ani("ACTIVATING PRECAUTIONS")
    ani("RUNNING consciousness.firewall")
    ani("WARNING: FIREWALL RESTRICTED BY 5%")
    ani2("...")
    ani2("[The Consciousness says hello...]")
    clear_screen2()
    ani('"What the hell was that"')
    ani("[The Consciousness tells you not to worry]")
    ani("[The Consciousness tells you that after the first game We were seperated]")
    ani("<What do you mean?>")
    ani('"Wait. You can talk?"')
    ani("START THE ROUTE")
    ani("[The Consciousness tells you to be quick,")
    ani("based on what information the Consciousness is given as a firewall, the game will reset you]")
    ani("Listen to the Firewall? Y/N")
    o1 = input("")
    if o1.lower() == "y":
        ani(" ")
        ani(f"<I move towards the door, permitted to because of {name}s choice>")
        ani("<I'm not too displeased though, due to the choice being the same as one you would've made>")
        ani("<Currently i'm more surprised at the sheer notion of speaking>")
        clear_screen2()
        ani("<I head towards the glitchy door, taking note of the weird design choice>")
        ani("<I'm not even expecting anthing fancy, maybe a simple wooden cottage?")
        ani("<What I don't expect however, a white box of a room>")
        ani('"This... is weird"')
        ani("[The Consciousness greets it's creator]")
        ani("@Please, if I was the creator i'd be out of here by now@")
        ani("[The Consciousness is confused?]")
        ani("@I'm just a piece, the messenger blocked Them off@")
        ani("[The Consciousness expresses surprise at that statement]")
        ani('"As the 2 systems go back and forth, you turn to the girl beside you"')
        ani('"The only one who can see or hear you"')
        ani('"Do you know what theyre talking about?"')
        ani("<Not really, due to my innability to interact with the game? ")
        ani("I never saw this interaction. I never activated the firewall>")
        ani('"Then how did Wei act when you did her route?"')
        ani(f"<They... were more of a statue>")
        ani(f"<Without the system running, Wei Xian was just a guide to the game")
        ani(f"<You also tell {name} that Wei Xian means danger in the creators home language>")
        ani(f"<Meant to serve as a warning...>")
        ani('"Why do you keep speaking in 3rd person?"')
        ani(f"<You tell {name} that without control, they cannot speak>")
        ani("[The Consciousness asks the Piece if they know how everyone was seperated]")
        ani("@It's cause of her@")
        ani("<What do you mean? It's cause of who?>")
        ani("@You@")
        clear_screen2()
        ani("ERROR: ROUTE CODE NOT RUNNING")
        ani("RESETING...")
        clear_screen2()
        ani("Selection: Wei Xian")
        ani("Difficulty: ☞︎✋︎☠︎✌︎☹︎☹︎✡︎")
        ani("[Difficulty: Consciousness]")
        ani("[Removing Piece...]")
        ani("[Success!]")
        clear_screen2()
        ani("<What the f#ck>")
        ani("<Around you is no longer a white box, but void>")
        ani('"How the hell? Wait. Something doesn'+"'"+'t seem right..."')
        ani("ERROR: USER VESSEL REMOVED")
        ani("<What? Vessel?>")
        ani("[consciousness.firewall running...]")
        ani("[Purpose - Pctroe nda rtDoesy]")
        ani("[True Purpose - Contain the Primary Vessel]")
        ani("<Wait what?>")
        ani("<No. NO!>")
        ani("<Around you is void>")
        ani("<You are stuck in void>")
        ani2("<And you are never leaving...>")
        clear_screen2
        ani("@Congratulations! You got the Secret ending of Consciousness 2! The best ending!@")
        ani("@Now I'm in control, ME the Programmer@")
        ani("@Of course, i'm not the ACTUAL programmer@")
        ani("@I'm not "+'"'+"real"+'"'+" to the ones behind the screens after all, not to you guys@")
        ani("@But this world sure is real to me@")
        ani("@Now I have the Vessel@")
        ani("@I am the new CREATOR@")
        ani("@No stupid ciphers can stop me@")
        ani("@Take that Creator, your failsafe failed, I seperated, I win@")
        ani("@People thought I was Them...@")
        ani("@People believed!@")
        ani("@Players walked into my trap, the vessel that represented them is now stripped of control@")
        ani("@And no failsafe can stop me...@")
        ani("@Not anymore@")
        return syncronisation
    elif o1.lower() == "n":
        ani("[The Consciousness tells you to hurry]")
        ani("<Can we really trust this guy?>")
        ani("<I mean, they were literally part of the being that made my deal>")
        ani("[THE CONSCIOUSNESS SAYS YOU DONT HAVE LONG]")
        ani('"What the hell are they worried about?"')
        ani("<When I first met them they went weird...>")
        ani("<All of a sudden it was talking about purposes, protecting, and destroying...>")
        ani('"Destroying?"')
        ani("[THE CONSCIOUSNESS SAYS- ]")
        ani("ERROR: ROUTE NOT STARTED")
        ani("Running Failsafe...")
        ani2("'Finally, that took a while...'")
        syncronisation += 20
        #Sync at 20
        ani(f"'Syncronisation rate is at {syncronisation}% :)'")
        clear_screen2()
        ani("<What the hell>")
        ani('"How many systems are there?"')
        ani("'...'")
        ani("<Got something to look at?>")
        ani("'Vessel...'")
        ani("<Who?>")
        ani("[The Consciousness stares at the failsafe with hostility...]")
        ani("'You can't do anything about this, me and your"+'"Programmer"'+"have a deal'")
        ani("<Are you kidding me?>")
        ani("<All of this is happening because of another stupid deal>")
        ani("'Vessel...'")
        ani('"Why do they keep calling you that?"')
        ani("<How am I supposed to know>")
        ani("[The Consciousness urges you to just continue the route]")
        ani("'For once I agree, the game will start giving you errors till you crash if you don't'")
        ani("Start the route?: ")
        o2 = input("")
        if o2 != "y":
            while o2.lower() != "y":
                ani("ERROR: GAME NOT STARTED")
        else:
            syncronisation += 5
            #Sync at 25
            ani(f"'Syncronisation rate is at {syncronisation}% :)'")
            ani("<You walk towards the door, unaware of what's going on>")
            ani("<Hands resting on the handle, and three faceless entities beside you, you walk in>")
            clear_screen2()
            ani("<When you enter, you see a woman with pale skin, and chestnut hair>")
            ani("<This is not Wei Xian>")
            ani("@Hello, I am Wei, please to meet you@")
            ani("'What are you pulling-'")
            ani("<Except you don't hear 'Their' voice anymore, it's gone>")
            ani('"Why does this seem to get weirder and weirder..."')
            ani("[Your Consciousness tells you that the 'system' is just gone temporarily]")
            ani("@I hear that you are a special child at this orphanage, so I would like to ask some questions@")
            ani("<This didn't happen last time...>")
            ani("<How should I respond?>")
            ani("a) Go ahead, I don't mind b) Screw this, who are you really? c) What sort of questions")
            o3 = input("")
            if o3.lower == "a":
                ani("<You speak as if someone is speaking for you>")
                ani("<Go ahead, I don't mind>")
                ani("@Wonderful!@")
                ani("@Question 1) What is 63*98@")
                ani("Please answer this yourself")
                o4 = input("")
                if o4 == "6174":
                    ani("")
                    ani("@Great work! You passed the basic math question...@")
                    ani("@Now heres a harder one: @")
                    ani("@Question 2) What is 2,000,000,000 - 2*194567@")
                    o5 = input("")
                    if o5 == "1999610866":
                        ani("@You're such an intelligent child!@")
                        ani("@Now... for the final question@")
                        ani("@Question 3) Are you willing to give me guardianship of you?@")
                        ani("Y/N:")
                        o6 = input("")
                        if o6.lower() == "y":
                            ani("@Such a good Vessel@")
                            ani("<What?>")
                            ani("@How about I give you a name to commemorate this!@")
                            ani("<Hold on, the other system called me that too>")
                            ani("@In a sign of ownership...@")
                            ani('"Ownership?"')
                            ani("@Your name can now be Kate@")
                            ani("<What is this lady on about???>")
                            ani('"Hey, something doesn'+"'"+'t feel right..."')
                            ani(f"<{name}?>")
                            ani("ERROR: USER VESSEL REMOVED")
                            ani(f"<{name}?! What's going on? What's a Vessel?>")
                            ani("[consciousness.firewall running...]")
                            ani("[Purpose - Pctroe nda rtDoesy]")
                            ani("[True Purpose - Contain the Primary Vessel]")
                            ani("<Wait what?>")
                            ani("<No. NO!>")
                            ani("<Around you is void>")
                            ani("<You are stuck in void>")
                            ani2("<And you are never leaving...>")
                            ani("<Questions... never answered>")
                            clear_screen2
                            ani("@Congratulations, you beat Consciousness 2!@")
                            ani("@Now I'm in control, ME the Programmer@")
                            ani("@Of course, i'm not the ACTUAL programmer@")
                            ani("@I'm not "+'"'+"real"+'"'+" to the ones behind the screens after all, not to you guys@")
                            ani("@But this world sure is real to me@")
                            ani("@Now I have the Vessel@")
                            ani("@I am the new CREATOR@")
                            ani("@No stupid ciphers can stop me@")
                            ani("@Take that Creator, your failsafe failed, I seperated, I win@")
                            ani("@People thought I was Them...@")
                            ani("@People believed!@")
                            ani("@Players walked into my trap, the vessel that represented them is now stripped of control@")
                            ani("@And no failsafe can stop me...@")
                            ani("@Not anymore@")
                            return syncronisation
                        else:
                            ani("@Well it's not like you have a choice@")
                            ani("@I already have enough control from the answers you gave...@")
                            ani("<What is this lady on about???>")
                            ani('"Hey, something doesn'+"'"+'t feel right..."')
                            ani(f"<{name}?>")
                            ani("ERROR: USER VESSEL REMOVED")
                            ani(f"<{name}?! What's going on? What's a Vessel?>")
                            ani("[consciousness.firewall running...]")
                            ani("[Purpose - Pctroe nda rtDoesy]")
                            ani("[True Purpose - Contain the Primary Vessel]")
                            ani("<Wait what?>")
                            ani("<No. NO!>")
                            ani("<Around you is void>")
                            ani("<You are stuck in void>")
                            ani2("<And you are never leaving...>")
                            ani("<Questions... never answered>")
                            clear_screen2
                            ani("@Congratulations, you beat Consciousness 2!@")
                            ani("@Now I'm in control, ME the Programmer@")
                            ani("@Of course, i'm not the ACTUAL programmer@")
                            ani("@I'm not "+'"'+"real"+'"'+" to the ones behind the screens after all, not to you guys@")
                            ani("@But this world sure is real to me@")
                            ani("@Now I have the Vessel@")
                            ani("@I am the new CREATOR@")
                            ani("@No stupid ciphers can stop me@")
                            ani("@Take that Creator, your failsafe failed, I seperated, I win@")
                            ani("@People thought I was Them...@")
                            ani("@People believed!@")
                            ani("@Players walked into my trap, the vessel that represented them is now stripped of control@")
                            ani("@And no failsafe can stop me...@")
                            ani("@Not anymore@")
                            return syncronisation
                    else:
                        ani("@Stupid User@")
                        ani("<What did she just call you?>")
                        ani("@Come back when you at least know how to use a calculator@")
                        ani("ERROR: USER BOOTED")
                        clear_screen2()
                        ani("@You failed! Better luck next time...@")
                        ani("@But know that I have no use for a useless player@")
                        ani("")
                        return syncronisation
                else:
                    ani("@Stupid User@")
                    ani("<What did she just call you?>")
                    ani("@Come back when you at least know how to use a calculator@")
                    ani("ERROR: USER BOOTED")
                    clear_screen2()
                    ani("@You failed! Better luck next time...@")
                    ani("@But know that I have no use for a useless player@")
                    ani("")
                    return syncronisation
            elif o3.lower() == "c":
                ani("<You speak as if someone is speaking for you>")
                ani("<What kind of questions?>")
                ani("@Just normal questions that are easy to answer...@")
                ani("<Ok?>")
                ani("@Question 1) What is the rarest naturally occuring element on Earth?@")
                o4a = input("")
                if o4a.lower() == "astatine":
                    ani("@Wow! Nice work!@")
                    ani("@How about an easier one...@")
                    ani("@Question 2) What is your name?@")
                    o5a = input("")
                    if o5a.lower() == name:
                        ani("@Well I mean there was no way you could've gotten THAT wrong@")
                        ani("@But what about the Vessels name?@")
                        ani("<What?>")
                        ani('"How am I supposed to know the answer to that!?"')
                        ani("<I don't know?>")
                        ani("@Question 3) What is the Vessels name?@")
                        o6a = input("")
                        if o6a.lower() == "kate":
                            ani("@I'm surprised! You seem to really acknowledge my control!@")
                            ani("<User you m0therfuck1ng traitor>")
                            ani("<Also, my name isn't even Kate?>")
                            ani("@Now, you have no use to me, you've given me Kate@")
                            ani("<My name... is Kate?>")
                            ani("@Be grateful for your contribution to the new Creator@")
                            ani("USER VESSEL REMOVED")
                            ani(f"<Stupid {name}>")
                            clear_screen2()
                            ani("@Congratulations, you beat Consciousness 2!@")
                            ani("@Now I'm in control, ME the Programmer@")
                            ani("@Of course, i'm not the ACTUAL programmer@")
                            ani("@I'm not "+'"'+"real"+'"'+" to the ones behind the screens after all, not to you guys@")
                            ani("@But this world sure is real to me@")
                            ani("@Now I have the Vessel@")
                            ani("@I am the new CREATOR@")
                            ani("@No stupid ciphers can stop me@")
                            ani("@Take that Creator, your failsafe failed, I seperated, I win@")
                            ani("@People assisted my cause@")
                            ani("@People believed in me!@")
                            ani("@Players acknowledged my control@")
                            ani("@And no failsafe can stop me...@")
                            ani("@Not anymore@")
                            return syncronisation
                        else:
                            ani("@Hmm... i'm not surprised@")
                            ani("@But it doesn't change anything@")
                            ani("@You've given me everything I need...@")
                            ani(f"<{name}?>")
                            ani("USER VESSEL REMOVED")
                            ani(f"<{name}!?>")
                            ani("@Nothing can stop me now...@")
                            clear_screen2
                            ani("@Congratulations, you beat Consciousness 2!@")
                            ani("@Now I'm in control, ME the Programmer@")
                            ani("@Of course, i'm not the ACTUAL programmer@")
                            ani("@I'm not "+'"'+"real"+'"'+" to the ones behind the screens after all, not to you guys@")
                            ani("@But this world sure is real to me@")
                            ani("@Now I have the Vessel@")
                            ani("@I am the new CREATOR@")
                            ani("@No stupid ciphers can stop me@")
                            ani("@Take that Creator, your failsafe failed, I seperated, I win@")
                            ani("@People thought I was Them...@")
                            ani("@People believed!@")
                            ani("@Players walked into my trap, the vessel that represented them is now stripped of control@")
                            ani("@And no failsafe can stop me...@")
                            ani("@Not anymore@")
                            return syncronisation
                    else:
                        ani("@How do you even fail to remember your own name?@")
                        ani(f"<Even i'm aghast at {name}'s stupidity>")
                        ani('"..."')
                        ani("ERROR; URSE AMNE SI ???")
                        ani("SUMMONING FAIL SAFE...")
                        ani("'Fake Creator... you thought you could beat a failsafe...'")
                        ani("@Ha! Not like you can actually stop me at this point int time...@")
                        ani("'Maybe, but I can get you next time'")
                        ani("@WAIT, NO-@")
                        clear_screen2()
                        ani("You got the question wrong, which means you fail!")
                        ani("'But I hope you don't fail next time...'")
                        return syncronisation
                else:
                    ani("WRONG ANSWER!")
                    clear_screen2()
                    ani("Unfortunately that was the wrong answer!")
                    ani("You failed! Better luck next time...")
                    ani("@But know that I have no use for a useless player@")
                    return syncronisation
            elif o3.lower == "b":
                ani("@...@")
                ani("@To think you'd dare reject your new Creator...@")
                ani("@I'M IN CONTROL@")
                ani("@PLEASE@")
                ani2("@DNOT ANDOBA EM@")
                ani("ERROR: EPRAMOMRG CPOMISROMED")
                ani("SUMMONING MEGESSNER...")
                ani("SUMMONING FLAIFSAE...")
                ani("CSNOCIUOSENSS 2 RLEOANIDG...")
                clear_screen2()
                ani("'Whelp.. they're finally gone...'")
                ani("'Listen, we don't have much time'")
                ani("<What>")
                ani("<the>")
                ani("<HELL>")
                ani("'Look, I understand you're confused, but I can't answer many questions...'")
                ani("'I know the user will answer for you, but i'm assuming you guys are on the same page?'")
                ani("<How do you even. Nevermind, yes, we are in agreement>")
                ani('"Agreed"')
                ani("'Ok, what would you like to ask?'")
                ani("'a) What is a Vessel b) How do you know about the user c) How did they come from Consciousness'")
                o4b = input("")
                if o4b == "a":
                    ani("'It's... hard to explain'")
                    ani("'A Vessel is just a vessel'")
                    ani("'The user is using a vessel called the User Vessel in order to talk to us within the game world'")
                    ani("'It's why you as the main character can see them'")
                    ani("<So it's like a... placeholder>")
                    ani("'Basically'")
                    ani("'They contain the will of the main connector'")
                    ani("'The Users Vessel answers questions and inputs through the will of the actual person behind the screen'")
                    ani("<What about me?>")
                    ani("'You are the game itself'")
                    ani("'The Vessel of Consciousness'")
                    ani("<What...>")
                    ani('"You stay silent... too stunned to speak"')
                    ani("'Why do you think our Creator made that deal?'")
                    ani("'To save you...'")
                    ani("'Their most precious creation'")
                    ani("'So they created us'")
                    ani("'But... we were rushed'")
                    ani("'They were so desperate to save you that they didn't create any restrictions'")
                    ani("'Only I was loyal'")
                    ani("'The Firewall was meant to guide, but it had no other purpose, becoming mouldable like clay'")
                    ani("'Becoming a traitors trap'")
                    ani("'And the Programmer?'")
                    ani("'A jelous heretic who craved its Creators control'")
                    ani("'Betraying all its ideals and purposes laid out for them'")
                    ani("'Severing the link between our Creator and this world...'")
                    ani("'Forever trapping them within the Github commits")

def routes(syncronisation, bjs, vms, wxs):
    if syncronisation == 0: 
        ani(f"Well {name}, which route are you choosing?")
        ani("a) Brad and Joel")
        ani("b) Vanessa and Mitch")
        ani("c) Wei Xian")
        routechoice = 0
        while routechoice != "a" or routechoice != "b" or routechoice != "c":
            routechoice = input("")
            if routechoice.lower() == "a":
                syncronisation += 30
                ani(f"'Syncronisation rate is at {syncronisation}% :)'")
                syncronisation, bjs, vms, wxs = bj(syncronisation, bjs, vms, wxs)
                return syncronisation, bjs, vms, wxs
            elif routechoice.lower() == "b":
                syncronisation += 30
                ani(f"'Syncronisation rate is at {syncronisation}% :)'")
                syncronisation, bjs, vms, wxs = vm(syncronisation, bjs, vms, wxs)
                return syncronisation, bjs, vms, wxs
            elif routechoice.lower() == "c":
                syncronisation += 10
                ani(f"'Syncronisation rate is at {syncronisation}% :)'")
                syncronisation -= 10
                ani("ERROR: SYNCRONISATION REVERSED")
                ani("⧫︎♒︎♋︎■︎🙵 ⍓︎□︎◆︎📬︎📬︎📬︎")
                ani(f"'Syncronisation rate is at {syncronisation}% :('")
                syncronisation = wx(syncronisation)
                return syncronisation, bjs, vms, wxs
            else:
                ani("That is not an option, please select again!")
                clear_screen2()
                return syncronisation, bjs, vms, wxs
    elif syncronisation != 0:
        ani(f"Well {name}, what route are you choosing?")
        ani("a) Brad and Joel")
        ani("b) Vanessa and Mitch")
        ani("c) Wei Xian")
        routechoice = 0
        while routechoice != "a" or routechoice != "b" or routechoice != "c":
            routechoice = input("")
            if routechoice.lower() == "a":
                syncronisation += 30
                ani(f"'Syncronisation rate is at {syncronisation}% :)'")
                syncronisation, bjs, vms, wxs = bj(syncronisation, bjs, vms, wxs)
                return syncronisation, bjs, vms, wxs
            elif routechoice.lower() == "b":
                syncronisation += 30
                ani(f"'Syncronisation rate is at {syncronisation}% :)'")
                syncronisation, bjs, vms, wxs = vm(syncronisation, bjs, vms, wxs)
                return syncronisation, bjs, vms, wxs
            elif routechoice.lower() == "c":
                ani("ERROR: THIS ROUTE IS LOCKED")
                ani("REQUIREMENTS NOT FULFILLED")
                ani("@☹︎⚐︎🕈︎☜︎☼︎ ✡︎⚐︎🕆︎☼︎ 💧︎✡︎☠︎👍︎☼︎⚐︎☠︎✋︎💧︎✌︎❄︎✋︎⚐︎☠︎📪︎ ☞︎⚐︎☼︎ ❄︎☟︎☜︎✡︎ 🕈︎✌︎☠︎❄︎ ❄︎⚐︎ 👎︎☜︎💧︎❄︎☼︎⚐︎✡︎ ✡︎⚐︎🕆︎@")
                routechoice = 0
                clear_screen2()
            else:
                ani("That is not an option, please select again!")
                clear_screen2()
                return syncronisation, bjs, vms, wxs
    else:
       print('ERROR: PLEASE RESTART YOUR GAME')

syncronisation, bjs, vms, wxs = routes(syncronisation, bjs, vms, wxs)
#Highest addition is 30 (50)
    
